[project]
# defaults to basename of pwd 
# slug = "sandbox"

[sources.structured-json]
type = "file"
path = "logs/json.log"
parser = "json"
tags = ["json", "structured"]

[sources.app-logfmt]
type = "file"
path = "logs/logfmt.log"
parser = "logfmt"
tags = ["logfmt", "structured"]

[sources.php-monolog]
type = "file"
path = "logs/monolog.log"
parser = "monolog"
tags = ["monolog", "php"]

[sources.system-syslog]
type = "file"
path = "logs/syslog.log"
parser = "syslog"
tags = ["syslog", "system"]

[sources.web-access]
type = "file"
path = "logs/access.log"
parser = "clf"
tags = ["clf", "http"]

[sources.plaintext]
type = "file"
path = "logs/plain.log"
parser = "line"
tags = ["plain", "fallback"]

[sources.auto-mixed]
type = "file"
path = "logs/mixed.log"
parser = "auto"
tags = ["auto", "mixed"]
